---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: un-install apache2 package
    apt:
      name: apache2
      state: absent

  - name: un-install php support for apache
    apt:
      name: libapache2-mod-php
      state: absent